version: '3.8'

services:
  document-scanner:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./credentials:/app/credentials:ro
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/key.json
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - document-scanner
    restart: unless-stopped
    profiles:
      - production
